#spring:
#  datasource:
##    druid:
##          db-type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          filters: stat
#          initial-size: 10
#          log-abandoned: true
#          max-active: 30
#          max-open-prepared-statements: 20
#          max-wait: 60000
#          min-evictable-idle-time-millis: 30000
#          min-idle: 10
#          remove-abandoned: true
#          remove-abandoned-timeout: 1800
#          test-on-borrow: false
#          test-on-return: false
#          test-while-idle: true
#          time-between-eviction-runs-millis: 60000
#          url: jdbc:mysql://127.0.0.1:3306/mixture?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#          validation-query: SELECT 1
#mybatis:
#  mapperLocations: classpath:java/com/bugull/locker/mapping/*.xml